name: Major Fail
favicon: null
layout_spectrum: 0.8702627937309444
typography_spectrum: 0.16408274811692536
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4355385049711913
  lightness: 0.5149730748962611
  saturation: 0.14764195238240063
  rhythmicContrast: 0.7643597710411996
purpose: []
